FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80 443 5000

ENV UI_URL=*

ENV RABBITMQ_HOST=host.docker.internal
ENV RABBITMQ_PORT=31672
ENV RABBITMQ_USER=guest
ENV RABBITMQ_PASSWORD=guest
ENV RABBITMQ_VHOST=/
ENV RABBITMQ_HEARTBEAT=60
ENV RABBITMQ_NER_EXCHANGE=""
ENV RABBITMQ_NER_QUEUE="ner"
ENV RABBITMQ_NER_ROUTING_KEY=""

ENV SIGNALR_MAXIMUM_RECEIVE_MESSAGE_SIZE=32000

ENV ASPNETCORE_ENVIRONMENT=Development

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["SC 4.0.sln", "SC 4.0/"]
COPY ["NERService/NERService.csproj", "NERService/"]
COPY ["RabbitMQ/RabbitMQHelper.csproj", "RabbitMQHelper/"]

RUN dotnet restore "NERService/NERService.csproj"
COPY . .
WORKDIR "/src/NERService"
RUN dotnet build "NERService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "NERService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "NERService.dll"]