apiVersion: apps/v1
kind: Deployment
metadata:
  name: ner-service
spec:
  selector:
    matchLabels:
      app: ner-service
  template:
    metadata:
      labels:
        app: ner-service
    spec:
      containers:
        - name: ner-service
          image: jonathanchewst/nerservice:1.0.0
          env:
            - name: "UI_URL"
              value: "*"
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Development"
            - name: "RABBITMQ_HOST"
              value: "host.docker.internal"
            - name: "RABBITMQ_PORT"
              value: "31672"
            - name: "RABBITMQ_USER"
              value: "guest"
            - name: "RABBITMQ_PASSWORD"
              value: "guest"
            - name: "RABBITMQ_TRANSCRIPTION_EXCHANGE"
              value: ""
            - name: "RABBITMQ_TRANSCRIPTION_QUEUE"
              value: "ner"
            - name: "RABBITMQ_TRANSCRIPTION_ROUTING_KEY"
              value: ""
          resources:
            limits:
              memory: "500Mi"
              cpu: 500m
            requests:
              cpu: 200m
          ports:
            - containerPort: 80
---
# SERVICE
# add in entry for ingress in ingress repo and run jenkins pipeline for ingress to update 
apiVersion: v1
kind: Service
metadata:
  name: ner-service
  labels:
    app: ner-service
spec:
  ports:
  - targetPort: 80
    port: 80
    protocol: TCP
  selector:
    app: ner-service
  type: ClusterIP